"""Safe YAML writer — never overwrite without force."""

from __future__ import annotations

from pathlib import Path

import yaml

from moex_standard_linkml.solution_xlsx.diagnostics import Diagnostic, Severity, SourceRef

BOOTSTRAP_COMMENT = (
    "# bootstrap-generated by moex-model import-solution (ADR-022) — edit freely\n"
)


class WriteSkipped(Exception):
    """Target exists and force was not set."""

    def __init__(self, path: Path, alt: Path) -> None:
        self.path = path
        self.alt = alt
        super().__init__(f"exists: {path}; wrote {alt}")


def dump_yaml(data: dict, path: Path, *, header_comment: bool = True) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    body = yaml.safe_dump(
        data,
        sort_keys=False,
        allow_unicode=True,
        default_flow_style=False,
    )
    text = (BOOTSTRAP_COMMENT + body) if header_comment else body
    path.write_text(text, encoding="utf-8")


def write_yaml_safe(
    data: dict,
    target: Path,
    *,
    force: bool,
    report_dir: Path,
    header_comment: bool = True,
) -> tuple[Path, Diagnostic | None]:
    """
    Write to target if missing or force=True.
    Otherwise write to report_dir / target.name and return SXI-IO-001.
    """
    if target.exists() and not force:
        alt = report_dir / target.name
        dump_yaml(data, alt, header_comment=header_comment)
        diag = Diagnostic(
            code="SXI-IO-001",
            severity=Severity.WARNING,
            message_ru=(
                f"Файл уже существует, запись не поверх: {target}. "
                f"Черновик: {alt}"
            ),
            remediation="Проверьте diff и повторите с --force при необходимости.",
            source_ref=SourceRef(sheet="(filesystem)", row=0, column=str(target)),
            details={"target": str(target), "draft": str(alt)},
        )
        return alt, diag

    dump_yaml(data, target, header_comment=header_comment)
    return target, None
