"""Port: read-only ontology navigation (implemented by standard-owl adapters)."""

from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class OntologyProviderPort(Protocol):
    def label(self, iri: str) -> str | None: ...

    def definition(self, iri: str) -> str | None: ...

    def aliases(self, iri: str) -> tuple[str, ...]: ...

    def parents(self, iri: str, *, predicate: str = "rdfs:subClassOf") -> tuple[str, ...]: ...

    def children(self, iri: str, *, predicate: str = "rdfs:subClassOf") -> tuple[str, ...]: ...

    def search(self, query: str, *, limit: int = 50) -> tuple[str, ...]: ...

    def entities(self) -> tuple[str, ...]: ...
