"""One-way ModelPackage → DBML projection (ADR-006; no round-trip)."""

from __future__ import annotations

import hashlib
import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Literal

import yaml

Profile = Literal["logical", "physical"]

GENERATOR = "moex-dams-dbml/0.1"
HEADER_COLORS = {
    "logical": "#4285F4",
    "physical": "#0F9D58",
}

_IDENT_RE = re.compile(r"[^A-Za-z0-9_]+")


@dataclass(frozen=True)
class DbmlManifest:
    content_digest: str
    profile: str
    source_path: str
    generator: str = GENERATOR

    def to_dict(self) -> dict[str, str]:
        return {
            "content_digest": self.content_digest,
            "profile": self.profile,
            "source_path": self.source_path,
            "generator": self.generator,
        }


def _ident(raw: str | None, *, fallback: str) -> str:
    text = (raw or "").strip() or fallback
    cleaned = _IDENT_RE.sub("_", text)
    if cleaned and cleaned[0].isdigit():
        cleaned = f"t_{cleaned}"
    return cleaned or fallback


def _escape_note(text: str) -> str:
    return text.replace("'", "\\'")


def _column_line(
    *,
    name: str,
    type_name: str,
    required: bool,
    note: str | None = None,
) -> str:
    settings: list[str] = []
    if required:
        settings.append("not null")
    if note:
        settings.append(f"note: '{_escape_note(note)}'")
    if not settings:
        return f"  {name} {type_name}"
    return f"  {name} {type_name} [{', '.join(settings)}]"


def project_model_package_to_dbml(
    data: dict[str, Any],
    *,
    profile: Profile,
) -> str:
    """Project a ModelPackage mapping into DBML text for drawDB import."""
    if profile not in ("logical", "physical"):
        raise ValueError(f"unsupported profile: {profile}")

    color = HEADER_COLORS[profile]
    package_name = _ident(data.get("name"), fallback="model_package")
    lines: list[str] = [
        f"// Generated by {GENERATOR} profile={profile}",
        f"// source package_id={data.get('element_id') or package_name}",
        "",
        f"Project {package_name} {{",
        f"  database_type: 'DAMS {profile} projection'",
        f"  Note: 'One-way DBML from ModelPackage (ADR-006). Not canonical.'",
        "}",
        "",
    ]

    # element_id → (table_ident, column_ident)
    col_index: dict[str, tuple[str, str]] = {}
    table_names: set[str] = set()

    if profile == "logical":
        for entity in data.get("logical_entities") or []:
            if not isinstance(entity, dict):
                continue
            tname = _ident(entity.get("name"), fallback="LogicalEntity")
            # uniquify
            base = tname
            n = 2
            while tname in table_names:
                tname = f"{base}_{n}"
                n += 1
            table_names.add(tname)
            note_bits = []
            if entity.get("element_id"):
                note_bits.append(f"element_id={entity['element_id']}")
            if entity.get("title"):
                note_bits.append(str(entity["title"]))
            lines.append(f"Table {tname} [headercolor: {color}] {{")
            if note_bits:
                lines.append(f"  Note: '{_escape_note('; '.join(note_bits))}'")
            for attr in entity.get("attributes") or []:
                if not isinstance(attr, dict):
                    continue
                cname = _ident(attr.get("name"), fallback="attr")
                ctype = _ident(attr.get("logical_type"), fallback="string")
                required = bool(attr.get("required"))
                aid = attr.get("element_id")
                note = str(aid) if aid else None
                lines.append(
                    _column_line(
                        name=cname,
                        type_name=ctype,
                        required=required,
                        note=note,
                    )
                )
                if aid:
                    col_index[str(aid)] = (tname, cname)
            lines.append("}")
            lines.append("")
    else:
        for obj in data.get("physical_objects") or []:
            if not isinstance(obj, dict):
                continue
            tname = _ident(obj.get("name"), fallback="PhysicalObject")
            base = tname
            n = 2
            while tname in table_names:
                tname = f"{base}_{n}"
                n += 1
            table_names.add(tname)
            kind = obj.get("object_kind") or "unknown"
            note_bits = [f"object_kind={kind}"]
            if obj.get("element_id"):
                note_bits.append(f"element_id={obj['element_id']}")
            if obj.get("title"):
                note_bits.append(str(obj["title"]))
            lines.append(f"Table {tname} [headercolor: {color}] {{")
            lines.append(f"  Note: '{_escape_note('; '.join(note_bits))}'")
            for field in obj.get("physical_fields") or []:
                if not isinstance(field, dict):
                    continue
                cname = _ident(
                    field.get("native_name") or field.get("name"),
                    fallback="field",
                )
                ctype = _ident(field.get("native_type"), fallback="string")
                required = bool(field.get("required"))
                fid = field.get("element_id")
                note = str(fid) if fid else None
                lines.append(
                    _column_line(
                        name=cname,
                        type_name=ctype,
                        required=required,
                        note=note,
                    )
                )
                if fid:
                    col_index[str(fid)] = (tname, cname)
            lines.append("}")
            lines.append("")

    # Cross-layer field mappings → Ref when both ends are in this projection.
    # Logical profile: only when both ends are logical attrs (rare).
    # Physical profile: field_mapping logical→physical typically only has
    # physical end in index; skip unless both present.
    refs: list[str] = []
    for mapping in data.get("mappings") or []:
        if not isinstance(mapping, dict):
            continue
        if mapping.get("mapping_type") != "field_mapping":
            continue
        sources = [str(x) for x in (mapping.get("source_refs") or [])]
        targets = [str(x) for x in (mapping.get("target_refs") or [])]
        for src in sources:
            for tgt in targets:
                if src not in col_index or tgt not in col_index:
                    continue
                st, sc = col_index[src]
                tt, tc = col_index[tgt]
                refs.append(f"Ref: {st}.{sc} > {tt}.{tc}")

    if refs:
        lines.append("// field_mapping refs (both ends in projected profile)")
        lines.extend(refs)
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def write_dbml_artifact(
    *,
    implementation_path: Path,
    out_path: Path,
    profile: Profile,
) -> DbmlManifest:
    """Load ModelPackage YAML, write DBML + sidecar ``*.manifest.json``."""
    raw = yaml.safe_load(implementation_path.read_text(encoding="utf-8"))
    if not isinstance(raw, dict):
        raise ValueError(f"expected ModelPackage mapping in {implementation_path}")
    text = project_model_package_to_dbml(raw, profile=profile)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    data = text.encode("utf-8")
    out_path.write_bytes(data)
    digest = "sha256:" + hashlib.sha256(data).hexdigest()
    manifest = DbmlManifest(
        content_digest=digest,
        profile=profile,
        source_path=str(implementation_path),
    )
    manifest_path = out_path.with_suffix(out_path.suffix + ".manifest.json")
    if out_path.suffix.lower() == ".dbml":
        manifest_path = out_path.with_name(out_path.name + ".manifest.json")
    manifest_path.write_text(
        json.dumps(manifest.to_dict(), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return manifest
