"""One-way ModelPackage → DBML projection (ADR-006; no round-trip)."""

from __future__ import annotations

import hashlib
import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Literal

import yaml

Profile = Literal["logical", "physical"]

GENERATOR = "moex-dams-dbml/0.1"
HEADER_COLORS = {
    "logical": "#4285F4",
    "physical": "#0F9D58",
}

_IDENT_RE = re.compile(r"[^A-Za-z0-9_]+")


@dataclass(frozen=True)
class DbmlManifest:
    content_digest: str
    profile: str
    source_path: str
    generator: str = GENERATOR

    def to_dict(self) -> dict[str, str]:
        return {
            "content_digest": self.content_digest,
            "profile": self.profile,
            "source_path": self.source_path,
            "generator": self.generator,
        }


def _ident(raw: str | None, *, fallback: str) -> str:
    text = (raw or "").strip() or fallback
    cleaned = _IDENT_RE.sub("_", text)
    if cleaned and cleaned[0].isdigit():
        cleaned = f"t_{cleaned}"
    return cleaned or fallback


def _escape_note(text: str) -> str:
    return text.replace("'", "\\'")


def _column_line(
    *,
    name: str,
    type_name: str,
    required: bool,
    note: str | None = None,
) -> str:
    settings: list[str] = []
    if required:
        settings.append("not null")
    if note:
        settings.append(f"note: '{_escape_note(note)}'")
    if not settings:
        return f"  {name} {type_name}"
    return f"  {name} {type_name} [{', '.join(settings)}]"


def project_model_package_to_dbml(
    data: dict[str, Any],
    *,
    profile: Profile,
) -> str:
    """Project a ModelPackage mapping into DBML text for drawDB import."""
    if profile not in ("logical", "physical"):
        raise ValueError(f"unsupported profile: {profile}")

    color = HEADER_COLORS[profile]
    package_name = _ident(data.get("name"), fallback="model_package")
    lines: list[str] = [
        f"// Generated by {GENERATOR} profile={profile}",
        f"// source package_id={data.get('element_id') or package_name}",
        "",
        f"Project {package_name} {{",
        f"  database_type: 'DAMS {profile} projection'",
        f"  Note: 'One-way DBML from ModelPackage (ADR-006). Not canonical.'",
        "}",
        "",
    ]

    # element_id → (table_ident, column_ident)
    col_index: dict[str, tuple[str, str]] = {}
    # entity/object element_id → (table_ident, default_column for Refs)
    entity_table: dict[str, str] = {}
    entity_default_col: dict[str, str] = {}
    table_names: set[str] = set()

    if profile == "logical":
        for entity in data.get("logical_entities") or []:
            if not isinstance(entity, dict):
                continue
            tname = _ident(entity.get("name"), fallback="LogicalEntity")
            # uniquify
            base = tname
            n = 2
            while tname in table_names:
                tname = f"{base}_{n}"
                n += 1
            table_names.add(tname)
            eid = entity.get("element_id")
            if eid:
                entity_table[str(eid)] = tname
            note_bits = []
            if eid:
                note_bits.append(f"element_id={eid}")
            if entity.get("title"):
                note_bits.append(str(entity["title"]))
            lines.append(f"Table {tname} [headercolor: {color}] {{")
            if note_bits:
                lines.append(f"  Note: '{_escape_note('; '.join(note_bits))}'")
            default_col: str | None = None
            for attr in entity.get("attributes") or []:
                if not isinstance(attr, dict):
                    continue
                cname = _ident(attr.get("name"), fallback="attr")
                ctype = _ident(attr.get("logical_type"), fallback="string")
                required = bool(attr.get("required"))
                aid = attr.get("element_id")
                note = str(aid) if aid else None
                lines.append(
                    _column_line(
                        name=cname,
                        type_name=ctype,
                        required=required,
                        note=note,
                    )
                )
                if aid:
                    col_index[str(aid)] = (tname, cname)
                if default_col is None:
                    default_col = cname
                elif attr.get("logical_type") == "identifier":
                    default_col = cname
            if eid and default_col:
                entity_default_col[str(eid)] = default_col
            lines.append("}")
            lines.append("")
    else:
        for obj in data.get("physical_objects") or []:
            if not isinstance(obj, dict):
                continue
            tname = _ident(obj.get("name"), fallback="PhysicalObject")
            base = tname
            n = 2
            while tname in table_names:
                tname = f"{base}_{n}"
                n += 1
            table_names.add(tname)
            oid = obj.get("element_id")
            if oid:
                entity_table[str(oid)] = tname
            kind = obj.get("object_kind") or "unknown"
            note_bits = [f"object_kind={kind}"]
            if oid:
                note_bits.append(f"element_id={oid}")
            if obj.get("title"):
                note_bits.append(str(obj["title"]))
            lines.append(f"Table {tname} [headercolor: {color}] {{")
            lines.append(f"  Note: '{_escape_note('; '.join(note_bits))}'")
            default_col: str | None = None
            for field in obj.get("physical_fields") or []:
                if not isinstance(field, dict):
                    continue
                cname = _ident(
                    field.get("native_name") or field.get("name"),
                    fallback="field",
                )
                ctype = _ident(field.get("native_type"), fallback="string")
                required = bool(field.get("required"))
                fid = field.get("element_id")
                note = str(fid) if fid else None
                lines.append(
                    _column_line(
                        name=cname,
                        type_name=ctype,
                        required=required,
                        note=note,
                    )
                )
                if fid:
                    col_index[str(fid)] = (tname, cname)
                if default_col is None:
                    default_col = cname
            if oid and default_col:
                entity_default_col[str(oid)] = default_col
            lines.append("}")
            lines.append("")

    refs: list[str] = []

    # Logical relationships → named Refs (entity ends via default columns).
    if profile == "logical":
        for rel in data.get("relationships") or []:
            if not isinstance(rel, dict):
                continue
            src_id = str(rel.get("source_entity_ref") or "")
            tgt_id = str(rel.get("target_entity_ref") or "")
            if (
                src_id not in entity_table
                or tgt_id not in entity_table
                or src_id not in entity_default_col
                or tgt_id not in entity_default_col
            ):
                continue
            rname = _ident(rel.get("name"), fallback="rel")
            rid = rel.get("element_id")
            note = f" // element_id={rid}" if rid else ""
            refs.append(
                f"Ref {rname}: {entity_table[src_id]}.{entity_default_col[src_id]} "
                f"> {entity_table[tgt_id]}.{entity_default_col[tgt_id]}{note}"
            )

    # Physical FKs: field_mapping when both ends are physical fields in index;
    # also object-level mappings with both physical object ends (default cols).
    for mapping in data.get("mappings") or []:
        if not isinstance(mapping, dict):
            continue
        mtype = mapping.get("mapping_type")
        sources = [str(x) for x in (mapping.get("source_refs") or [])]
        targets = [str(x) for x in (mapping.get("target_refs") or [])]
        mid = mapping.get("element_id")
        mname = _ident(mapping.get("name"), fallback="map")
        note = f" // element_id={mid}" if mid else ""

        if mtype == "field_mapping":
            for src in sources:
                for tgt in targets:
                    if src not in col_index or tgt not in col_index:
                        continue
                    st, sc = col_index[src]
                    tt, tc = col_index[tgt]
                    refs.append(f"Ref {mname}: {st}.{sc} > {tt}.{tc}{note}")
        elif profile == "physical" and mtype in {
            "object_mapping",
            "entity_mapping",
        }:
            for src in sources:
                for tgt in targets:
                    if (
                        src not in entity_table
                        or tgt not in entity_table
                        or src not in entity_default_col
                        or tgt not in entity_default_col
                    ):
                        continue
                    refs.append(
                        f"Ref {mname}: {entity_table[src]}.{entity_default_col[src]} "
                        f"> {entity_table[tgt]}.{entity_default_col[tgt]}{note}"
                    )

    if refs:
        lines.append("// relationships / mappings as Refs")
        lines.extend(refs)
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def write_dbml_artifact(
    *,
    implementation_path: Path,
    out_path: Path,
    profile: Profile,
) -> DbmlManifest:
    """Load ModelPackage YAML, write DBML + sidecar ``*.manifest.json``."""
    raw = yaml.safe_load(implementation_path.read_text(encoding="utf-8"))
    if not isinstance(raw, dict):
        raise ValueError(f"expected ModelPackage mapping in {implementation_path}")
    text = project_model_package_to_dbml(raw, profile=profile)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    data = text.encode("utf-8")
    out_path.write_bytes(data)
    digest = "sha256:" + hashlib.sha256(data).hexdigest()
    manifest = DbmlManifest(
        content_digest=digest,
        profile=profile,
        source_path=str(implementation_path),
    )
    manifest_path = out_path.with_suffix(out_path.suffix + ".manifest.json")
    if out_path.suffix.lower() == ".dbml":
        manifest_path = out_path.with_name(out_path.name + ".manifest.json")
    manifest_path.write_text(
        json.dumps(manifest.to_dict(), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return manifest
