"""Generate moex_dams_contracts from DAMS LinkML schema via gen-pydantic."""

from __future__ import annotations

import hashlib
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SCHEMA = (
    REPO
    / "model-assets"
    / "specifications"
    / "moex-dams"
    / "0.1"
    / "schemas"
    / "moex-dams.yaml"
)
OUT_ROOT = REPO / "generated" / "contracts" / "moex-dams" / "0.1"
PKG_DIR = OUT_ROOT / "src" / "moex_dams_contracts"
INIT_PY = PKG_DIR / "__init__.py"
PYPROJECT = OUT_ROOT / "pyproject.toml"
MANIFEST = REPO / "generated" / "manifests" / "moex-dams-contracts.json"

HEADER = (
    "# Generated by gen-pydantic — do not edit by hand.\n"
    "# Regenerate: make generate-contracts\n"
    "#   or: python scripts/generate_contracts.py\n\n"
)

PYPROJECT_TOML = """\
[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "moex-dams-contracts"
version = "0.1.0"
description = "Generated Pydantic contracts for MOEX DAMS 0.1 (do not edit)"
requires-python = ">=3.11"
dependencies = ["pydantic>=2.6,<3.0"]

[tool.setuptools.packages.find]
where = ["src"]
"""


def main() -> int:
    if not SCHEMA.is_file():
        print(f"missing schema: {SCHEMA}", file=sys.stderr)
        return 1

    try:
        from linkml.generators.pydanticgen import PydanticGenerator
        from linkml.generators.pydanticgen.pydanticgen import MetadataMode
    except ImportError as exc:
        print(f"linkml required: {exc}", file=sys.stderr)
        return 1

    PKG_DIR.mkdir(parents=True, exist_ok=True)
    MANIFEST.parent.mkdir(parents=True, exist_ok=True)

    gen = PydanticGenerator(
        str(SCHEMA),
        metadata_mode=MetadataMode.NONE,
        extra_fields="forbid",
    )
    body = gen.serialize()
    if "class ModelPackage" not in body:
        print("generated output missing ModelPackage", file=sys.stderr)
        return 1

    INIT_PY.write_text(HEADER + body, encoding="utf-8")
    PYPROJECT.write_text(PYPROJECT_TOML, encoding="utf-8")

    digest = "sha256:" + hashlib.sha256(INIT_PY.read_bytes()).hexdigest()
    schema_digest = "sha256:" + hashlib.sha256(SCHEMA.read_bytes()).hexdigest()
    manifest = {
        "artifact_id": "moex:artifact:dams-contracts:0.1",
        "generator": "gen-pydantic",
        "generator_module": "linkml.generators.pydanticgen",
        "schema_path": SCHEMA.relative_to(REPO).as_posix(),
        "schema_digest": schema_digest,
        "output_path": INIT_PY.relative_to(REPO).as_posix(),
        "content_digest": digest,
        "package": "moex-dams-contracts",
        "generated_at": datetime.now(timezone.utc).isoformat(),
    }
    MANIFEST.write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(f"wrote {INIT_PY}")
    print(f"wrote {MANIFEST}")
    print(f"digest {digest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
