"""Generate moex_dams_contracts from DAMS LinkML schema via gen-pydantic."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from datetime import datetime, timezone
from importlib.metadata import PackageNotFoundError, version
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SCHEMA = (
    REPO
    / "model-assets"
    / "specifications"
    / "moex-dams"
    / "0.1"
    / "schemas"
    / "moex-dams.yaml"
)
DEFAULT_OUT_ROOT = REPO / "generated" / "contracts" / "moex-dams" / "0.1"
DEFAULT_MANIFEST = REPO / "generated" / "manifests" / "moex-dams-contracts.json"

HEADER = (
    "# Generated by gen-pydantic — do not edit by hand.\n"
    "# Regenerate: make generate-contracts\n"
    "#   or: python scripts/generate_contracts.py\n\n"
)

PYPROJECT_TOML = """\
[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "moex-dams-contracts"
version = "0.1.0"
description = "Generated Pydantic contracts for MOEX DAMS 0.1 (do not edit)"
requires-python = ">=3.11"
dependencies = ["pydantic>=2.6,<3.0"]

[tool.setuptools.packages.find]
where = ["src"]
"""


def _linkml_version() -> str:
    try:
        return version("linkml")
    except PackageNotFoundError:
        return "unknown"


def generate(*, out_root: Path, manifest_path: Path) -> tuple[Path, str]:
    """Write contracts package + manifest. Returns (init_py, content_digest)."""
    if not SCHEMA.is_file():
        raise FileNotFoundError(f"missing schema: {SCHEMA}")

    from linkml.generators.pydanticgen import PydanticGenerator
    from linkml.generators.pydanticgen.pydanticgen import MetadataMode

    pkg_dir = out_root / "src" / "moex_dams_contracts"
    init_py = pkg_dir / "__init__.py"
    pyproject = out_root / "pyproject.toml"

    pkg_dir.mkdir(parents=True, exist_ok=True)
    manifest_path.parent.mkdir(parents=True, exist_ok=True)

    gen = PydanticGenerator(
        str(SCHEMA),
        metadata_mode=MetadataMode.NONE,
        extra_fields="forbid",
    )
    body = gen.serialize()
    if "class ModelPackage" not in body:
        raise RuntimeError("generated output missing ModelPackage")

    # Force LF so Windows/Linux CI digests match (Path.write_text defaults to os.linesep).
    init_py.write_text(HEADER + body, encoding="utf-8", newline="\n")
    pyproject.write_text(PYPROJECT_TOML, encoding="utf-8", newline="\n")

    digest = "sha256:" + hashlib.sha256(init_py.read_bytes()).hexdigest()
    schema_digest = "sha256:" + hashlib.sha256(SCHEMA.read_bytes()).hexdigest()
    try:
        output_rel = init_py.relative_to(REPO).as_posix()
    except ValueError:
        output_rel = init_py.as_posix()

    stable = {
        "artifact_id": "moex:artifact:dams-contracts:0.1",
        "generator": "gen-pydantic",
        "generator_module": "linkml.generators.pydanticgen",
        "generator_version": _linkml_version(),
        "schema_path": SCHEMA.relative_to(REPO).as_posix(),
        "schema_digest": schema_digest,
        "output_path": output_rel,
        "content_digest": digest,
        "package": "moex-dams-contracts",
    }
    # Keep generated_at stable when content is unchanged so check_all leaves a clean tree.
    prev: dict = {}
    if manifest_path.is_file():
        try:
            prev = json.loads(manifest_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            prev = {}
    prev_stable = {k: prev.get(k) for k in stable}
    if prev_stable == stable and prev.get("generated_at"):
        generated_at = str(prev["generated_at"])
    else:
        generated_at = datetime.now(timezone.utc).isoformat()
    manifest = {**stable, "generated_at": generated_at}
    manifest_path.write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    return init_py, digest


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out-root",
        type=Path,
        default=DEFAULT_OUT_ROOT,
        help="Contracts package root (default: generated/contracts/moex-dams/0.1)",
    )
    parser.add_argument(
        "--manifest",
        type=Path,
        default=DEFAULT_MANIFEST,
        help="Manifest JSON path",
    )
    args = parser.parse_args(argv)

    try:
        init_py, digest = generate(out_root=args.out_root, manifest_path=args.manifest)
    except Exception as exc:
        print(f"generate_contracts failed: {exc}", file=sys.stderr)
        return 1

    print(f"wrote {init_py}")
    print(f"wrote {args.manifest}")
    print(f"digest {digest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
