"""Inventory of DAMS class roles and induced base slots (ADR-044, PR-0).

For every class of moex-dams.yaml (imports merged) prints its role
(ModelElement descendant / EmbeddedElement descendant / own identifier / none)
and the induced state of the base slots (element_id, name, title, description,
lifecycle_status, valid_from, valid_to, glossary_term_refs, tags).

Output is deterministic (sorted by class name) so that a later PR can diff
the "after" matrix against the committed "before" matrix.

Usage (repo root):
  .venv/Scripts/python.exe scripts/inventory_model_roles.py \\
      --csv docs/architecture/model-element-matrix-before.csv \\
      --md  docs/architecture/model-element-matrix-before.md
"""

from __future__ import annotations

import argparse
import csv
import io
from pathlib import Path

from linkml_runtime.utils.schemaview import SchemaView

REPO = Path(__file__).resolve().parents[1]
SCHEMA = (
    REPO
    / "model-assets"
    / "specifications"
    / "moex-dams"
    / "0.1"
    / "schemas"
    / "moex-dams.yaml"
)

BASE_SLOTS = (
    "element_id",
    "name",
    "title",
    "description",
    "lifecycle_status",
    "valid_from",
    "valid_to",
    "glossary_term_refs",
    "tags",
)

# Cell vocabulary: "-" slot absent, "req" required, "rec" recommended, "opt" optional.
ABSENT, REQ, REC, OPT = "-", "req", "rec", "opt"


def _module_hint(from_schema: str | None) -> str:
    if not from_schema:
        return ""
    # ids look like https://data.moex.com/dams/core/v0.1
    parts = from_schema.rstrip("/").split("/")
    if len(parts) >= 2 and parts[-1].startswith("v"):
        return parts[-2]
    return parts[-1]


def _role(sv: SchemaView, name: str) -> str:
    cls = sv.get_class(name)
    if cls.mixin:
        return "mixin"
    ancestors = set(sv.class_ancestors(name))
    if "ModelElement" in ancestors:
        return "ModelElement"
    if "EmbeddedElement" in ancestors:
        return "EmbeddedElement"
    return "none"


def _cell(slots: dict, slot: str) -> str:
    induced = slots.get(slot)
    if induced is None:
        return ABSENT
    if induced.required:
        return REQ
    if getattr(induced, "recommended", None):
        return REC
    return OPT


def build_rows(sv: SchemaView) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    for name in sorted(sv.all_classes()):
        cls = sv.get_class(name)
        slots = {s.name: s for s in sv.class_induced_slots(name)}
        own_ids = sorted(
            s.name for s in slots.values() if getattr(s, "identifier", None)
        )
        mixin_ancestors = set(sv.class_ancestors(name, mixins=True, reflexive=False))
        row = {
            "class": name,
            "module": _module_hint(cls.from_schema),
            "role": _role(sv, name),
            "abstract": "yes" if cls.abstract else "",
            "own_identifier": ",".join(own_ids),
            "is_a": str(cls.is_a or ""),
            "direct_mixins": ",".join(sorted(cls.mixins or [])),
            "slot_usage_description": (
                "yes" if "description" in (cls.slot_usage or {}) else ""
            ),
            "has_definition": "yes" if "HasDefinition" in mixin_ancestors else "",
        }
        for slot in BASE_SLOTS:
            row[slot] = _cell(slots, slot)
        rows.append(row)
    return rows


COLUMNS = (
    "class",
    "module",
    "role",
    "abstract",
    "own_identifier",
    "is_a",
    "direct_mixins",
    "slot_usage_description",
    "has_definition",
    *BASE_SLOTS,
)


def to_csv(rows: list[dict[str, str]]) -> str:
    buf = io.StringIO()
    writer = csv.DictWriter(buf, fieldnames=COLUMNS, lineterminator="\n")
    writer.writeheader()
    writer.writerows(rows)
    return buf.getvalue()


def to_md(rows: list[dict[str, str]]) -> str:
    lines = [
        "---",
        'status: Proposed',
        'version: "0.1"',
        "normative: false",
        "supersedes: []",
        "superseded_by: []",
        "---",
        "",
        "# ModelElement matrix (before ADR-044)",
        "",
        "Generated by `scripts/inventory_model_roles.py`; do not edit by hand.",
        "Cells: `-` slot absent, `req` required, `rec` recommended, `opt` optional.",
        "",
        "| " + " | ".join(COLUMNS) + " |",
        "|" + "|".join("---" for _ in COLUMNS) + "|",
    ]
    for row in rows:
        lines.append("| " + " | ".join(row[c] or " " for c in COLUMNS) + " |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--schema", type=Path, default=SCHEMA)
    parser.add_argument("--csv", type=Path)
    parser.add_argument("--md", type=Path)
    args = parser.parse_args()

    sv = SchemaView(str(args.schema))
    rows = build_rows(sv)
    csv_text = to_csv(rows)
    if args.csv:
        args.csv.parent.mkdir(parents=True, exist_ok=True)
        args.csv.write_text(csv_text, encoding="utf-8", newline="\n")
        print(f"wrote {args.csv}")
    if args.md:
        args.md.parent.mkdir(parents=True, exist_ok=True)
        args.md.write_text(to_md(rows), encoding="utf-8", newline="\n")
        print(f"wrote {args.md}")
    if not args.csv and not args.md:
        print(csv_text, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
