"""Inventory of invariant candidates (constraint matrix, PR-C0, ADR-045).

Scans normative / design prose and LinkML schema descriptions for
obligation and prohibition wording and writes a CSV of *candidates*. The
CSV is an input for manual selection of real invariants; it is **not**
the constraint matrix.

Sources
  * ``docs/adr/*.md``, ``docs/architecture/*.md`` (includes MODELING_ARCHITECTURE.md);
  * ``description`` and ``comments`` of classes, slots, slot_usage and attributes in
    every ``schemas/*.yaml`` of the DAMS specification (moex-dams.yaml + imported modules).

Markers (case-insensitive): должен/обязан/запрещено/не может/не допускается/
только если/только для, must/shall/only if/mutually exclusive/forbidden.

Output columns: file, line, quote, nearest (nearest known class or slot).
Output is deterministic (sorted by file, line).

``--list-rules`` prints every LinkML ``rules`` entry of the schema modules as
``file | class | index | description`` (exact baseline list used by the matrix).

Usage (repo root)::

    python scripts/inventory_invariants.py --csv docs/architecture/invariant-candidates.csv
    python scripts/inventory_invariants.py --list-rules
"""

from __future__ import annotations

import argparse
import csv
import re
import sys
from pathlib import Path
from typing import Any, Iterator

from ruamel.yaml import YAML

REPO = Path(__file__).resolve().parents[1]
SCHEMA_DIR = (
    REPO / "model-assets" / "specifications" / "moex-dams" / "0.1" / "schemas"
)
DOC_DIRS = (REPO / "docs" / "adr", REPO / "docs" / "architecture")

# Generated by this very PR series; scanning them would feed the inventory back on itself.
SELF_EXCLUDE = {
    "invariant-candidates.csv",
    "constraint-matrix-inventory-report.md",
    "constraint-matrix.md",
    "linkml-rules-support.md",
    "ADR-045-executable-constraint-matrix.md",
    "validation-helper-c1a-report.md",
}

MARKERS = (
    r"должен", r"должна", r"должно", r"должны", r"обязан\w*",
    r"запрещ\w*", r"не может", r"не могут", r"не допускается", r"не допускаются",
    r"только если", r"только для", r"только при", r"взаимоисключ\w*",
    r"must", r"shall", r"only if", r"mutually exclusive", r"forbidden",
)
MARKER_RE = re.compile(
    r"(?<!\w)(?:" + "|".join(MARKERS) + r")(?!\w)", re.IGNORECASE | re.UNICODE
)
HEADING_RE = re.compile(r"^#{1,6}\s+(.*)$")
TOKEN_RE = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")


def schema_files() -> list[Path]:
    return sorted(SCHEMA_DIR.glob("*.yaml"))


def _yaml() -> YAML:
    y = YAML(typ="rt")
    y.preserve_quotes = True
    return y


def load_schema(path: Path) -> Any:
    with path.open(encoding="utf-8") as fh:
        return _yaml().load(fh) or {}


def known_names(schemas: list[Path]) -> set[str]:
    names: set[str] = set()
    for path in schemas:
        data = load_schema(path)
        for section in ("classes", "slots", "enums", "types"):
            names.update((data.get(section) or {}).keys())
    return names


def _line(node: Any, key: str, default: int = 0) -> int:
    try:
        return int(node.lc.key(key)[0]) + 1
    except Exception:  # noqa: BLE001 - ruamel raises several types for plain scalars
        return default


def _texts(value: Any) -> Iterator[str]:
    if isinstance(value, str):
        yield value
    elif isinstance(value, list):
        for item in value:
            yield from _texts(item)


def _schema_nodes(data: Any) -> Iterator[tuple[str, Any]]:
    """Yield (owner_name, mapping) for classes, slots, slot_usage, attributes."""
    for section in ("classes", "slots"):
        for name, body in (data.get(section) or {}).items():
            if not hasattr(body, "get"):
                continue
            yield name, body
            if section == "classes":
                for sub in ("slot_usage", "attributes"):
                    for sname, sbody in (body.get(sub) or {}).items():
                        if hasattr(sbody, "get"):
                            yield f"{name}.{sname}", sbody


def schema_candidates(path: Path) -> Iterator[tuple[int, str, str]]:
    data = load_schema(path)
    for owner, body in _schema_nodes(data):
        for field in ("description", "comments", "notes"):
            if field not in body:
                continue
            base_line = _line(body, field)
            for text in _texts(body[field]):
                yield from _split_quote(text, base_line, owner)


def _split_quote(text: str, base_line: int, owner: str) -> Iterator[tuple[int, str, str]]:
    for offset, raw in enumerate(text.splitlines() or [text]):
        if MARKER_RE.search(raw):
            yield base_line + offset, " ".join(raw.split()), owner


def doc_candidates(path: Path, names: set[str]) -> Iterator[tuple[int, str, str]]:
    lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    in_front = bool(lines) and lines[0].strip() == "---"
    heading = ""
    for idx, raw in enumerate(lines, start=1):
        if in_front:
            if idx > 1 and raw.strip() == "---":
                in_front = False
            continue
        m = HEADING_RE.match(raw)
        if m:
            heading = m.group(1).strip()
        if not MARKER_RE.search(raw):
            continue
        nearest = _nearest_name(raw, names) or _nearest_back(lines, idx - 1, names) or heading
        yield idx, " ".join(raw.split()), nearest


def _nearest_name(text: str, names: set[str]) -> str:
    hits = [t for t in TOKEN_RE.findall(text) if t in names]
    return hits[0] if hits else ""


def _nearest_back(lines: list[str], index: int, names: set[str], span: int = 6) -> str:
    for back in range(index - 1, max(index - span, -1), -1):
        found = _nearest_name(lines[back], names)
        if found:
            return found
    return ""


def doc_files() -> list[Path]:
    out: list[Path] = []
    for d in DOC_DIRS:
        out.extend(p for p in sorted(d.glob("*.md")) if p.name not in SELF_EXCLUDE)
    return out


def rel(path: Path) -> str:
    return path.relative_to(REPO).as_posix()


def collect() -> list[tuple[str, int, str, str]]:
    schemas = schema_files()
    names = known_names(schemas)
    rows: list[tuple[str, int, str, str]] = []
    for path in doc_files():
        rows.extend((rel(path), ln, q, n) for ln, q, n in doc_candidates(path, names))
    for path in schemas:
        rows.extend((rel(path), ln, q, n) for ln, q, n in schema_candidates(path))
    rows.sort(key=lambda r: (r[0], r[1], r[2]))
    return rows


def list_rules() -> list[tuple[str, str, int, str]]:
    out: list[tuple[str, str, int, str]] = []
    for path in schema_files():
        data = load_schema(path)
        for cname, body in (data.get("classes") or {}).items():
            for idx, rule in enumerate((body or {}).get("rules") or []):
                out.append((path.name, cname, idx, str(rule.get("description", ""))))
    return out


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--csv", type=Path, help="write candidates to this CSV (repo-relative or absolute)")
    ap.add_argument("--list-rules", action="store_true", help="print all LinkML rules entries")
    args = ap.parse_args(argv)

    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")

    if args.list_rules:
        rules = list_rules()
        for fname, cname, idx, desc in rules:
            print(f"{fname} | {cname} | {idx} | {desc}")
        print(f"total rules: {len(rules)}")
        return 0

    rows = collect()
    if args.csv:
        out = args.csv if args.csv.is_absolute() else REPO / args.csv
        out.parent.mkdir(parents=True, exist_ok=True)
        with out.open("w", encoding="utf-8", newline="") as fh:
            w = csv.writer(fh, lineterminator="\n")
            w.writerow(["file", "line", "quote", "nearest"])
            w.writerows(rows)
        print(f"wrote {rel(out)}: {len(rows)} candidates")
    else:
        print(f"{len(rows)} candidates (use --csv to write)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
