"""Spike: polymorphic TechnicalAsset collection vs separate collections.

Runs against the live DAMS schema + a temporary ModelPackage extension.
Writes results to docs/migration/technical-asset-spike-report.md
"""

from __future__ import annotations

import json
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SCHEMA_DIR = REPO / "model-assets" / "specifications" / "moex-dams" / "0.1" / "schemas"
sys.path.insert(0, str(REPO / "apps" / "cli" / "src"))

SPIKE_SCHEMA = """
id: https://data.moex.com/dams/spike/technical-asset/v0.1
name: technical_asset_spike
imports:
  - linkml:types
  - moex-types
  - moex-registries
  - moex-governance
  - moex-core
  - moex-technical
prefixes:
  linkml: https://w3id.org/linkml/
  dams: https://data.moex.com/dams/
default_prefix: dams
default_range: string

classes:
  SpikePackagePoly:
    tree_root: true
    is_a: ModelPackage
    slots:
      - technical_assets
    slot_usage:
      technical_assets:
        range: TechnicalAsset
        multivalued: true
        inlined: true
        inlined_as_list: true

  SpikePackageSeparate:
    tree_root: true
    is_a: ModelPackage
    slots:
      - data_carriers
      - access_points
      - data_containers
      - execution_assets

slots:
  technical_assets:
    range: TechnicalAsset
    multivalued: true
    inlined: true
    inlined_as_list: true
  data_carriers:
    range: DataCarrier
    multivalued: true
    inlined: true
    inlined_as_list: true
  access_points:
    range: AccessPoint
    multivalued: true
    inlined: true
    inlined_as_list: true
  data_containers:
    range: DataContainer
    multivalued: true
    inlined: true
    inlined_as_list: true
  execution_assets:
    range: ExecutionAsset
    multivalued: true
    inlined: true
    inlined_as_list: true
"""

CARRIER = {
    "element_id": "dams:asset/spike/carrier1",
    "name": "carrier1",
    "description": "spike carrier",
    "lifecycle_status": "draft",
    "asset_namespace": "oracle://MDM",
    "qualified_name": "SCHEMA.T1",
    "system_ref": "eam:system/MDM",
    "asset_kind": "relational_table",
    "structure_ref": "oracle:SCHEMA.T1",
    "data_format": "relational",
    "direction": "internal",
}

ACCESS = {
    "element_id": "dams:asset/spike/api1",
    "name": "api1",
    "description": "spike access",
    "lifecycle_status": "draft",
    "asset_namespace": "https://api.example",
    "qualified_name": "/v1/clients",
    "system_ref": "eam:system/MDM",
    "asset_kind": "interface",
    "protocol": "https",
    "serves_refs": ["dams:asset/spike/carrier1"],
}

CONTAINER = {
    "element_id": "dams:asset/spike/db1",
    "name": "db1",
    "description": "spike container",
    "lifecycle_status": "draft",
    "asset_namespace": "oracle://MDM",
    "qualified_name": "MDM_DB",
    "system_ref": "eam:system/MDM",
    "asset_kind": "database",
    "containment_kind": "hierarchical",
}

EXECUTION = {
    "element_id": "dams:asset/spike/pipe1",
    "name": "pipe1",
    "description": "spike pipeline",
    "lifecycle_status": "draft",
    "asset_namespace": "airflow://cluster",
    "qualified_name": "dag.sync_clients",
    "system_ref": "eam:system/MDM",
    "asset_kind": "pipeline",
    "produces_refs": ["dams:asset/spike/carrier1"],
    "consumes_refs": ["dams:asset/spike/carrier1"],
}


def main() -> int:
    from linkml.generators.jsonschemagen import JsonSchemaGenerator
    from linkml.generators.pydanticgen import PydanticGenerator
    from linkml.validator import Validator
    from linkml_runtime.utils.schemaview import SchemaView

    lines: list[str] = []
    lines.append("# TechnicalAsset generator spike report\n")
    lines.append("Date: auto-generated by `scripts/spike_technical_asset_generators.py`\n")

    # Write spike schema next to real modules so relative imports resolve.
    spike_path = SCHEMA_DIR / "_spike_technical_asset.yaml"
    spike_path.write_text(SPIKE_SCHEMA.strip() + "\n", encoding="utf-8")
    tmp_path = Path(tempfile.mkdtemp(prefix="ta-spike-"))

    try:
        # --- Variant A: polymorphic collection ---
        lines.append("## Variant A: polymorphic `technical_assets`\n")
        try:
            sv = SchemaView(str(spike_path))
            _ = sv.all_classes()
            lines.append(f"- SchemaView load: OK (classes={len(sv.all_classes())})\n")
        except Exception as exc:  # noqa: BLE001
            lines.append(f"- SchemaView load: FAIL — `{exc}`\n")
            (REPO / "docs" / "migration" / "technical-asset-spike-report.md").write_text(
                "".join(lines), encoding="utf-8"
            )
            return 1

        has_designator = "asset_class" in (sv.all_slots() or {})
        lines.append(f"- `asset_class` designator present in schema: {has_designator}\n")

        try:
            py_code = PydanticGenerator(str(spike_path)).serialize()
            lines.append(f"- gen-pydantic: OK ({len(py_code)} chars)\n")
            for needle in ("technical_assets", "TechnicalAsset", "DataCarrier", "Union"):
                lines.append(f"  - pydantic mentions `{needle}`: {needle in py_code}\n")
            idx = py_code.find("technical_assets")
            snippet = py_code[max(0, idx - 80) : idx + 200] if idx >= 0 else ""
            lines.append(f"  - pydantic snippet around technical_assets:\n\n```\n{snippet}\n```\n")
        except Exception as exc:  # noqa: BLE001
            lines.append(f"- gen-pydantic: FAIL — `{exc}`\n")
            py_code = ""

        for flag in (False, True):
            try:
                js = JsonSchemaGenerator(
                    str(spike_path),
                    include_range_class_descendants=flag,
                    top_class="SpikePackagePoly",
                ).serialize()
                data = json.loads(js)
                defs = data.get("$defs") or data.get("definitions") or {}
                has_carrier = "DataCarrier" in defs
                has_ta = "TechnicalAsset" in defs
                props = data.get("properties") or {}
                ta_prop = props.get("technical_assets") or {}
                lines.append(
                    f"- gen-json-schema include_range_class_descendants={flag}: "
                    f"OK; DataCarrier in defs={has_carrier}; "
                    f"TechnicalAsset in defs={has_ta}; "
                    f"technical_assets prop keys={list(ta_prop.keys())}\n"
                )
                lines.append(
                    f"  - technical_assets schema fragment: `{json.dumps(ta_prop)[:400]}`\n"
                )
            except Exception as exc:  # noqa: BLE001
                lines.append(
                    f"- gen-json-schema include_range_class_descendants={flag}: FAIL — `{exc}`\n"
                )

        lines.append("\n## unique_keys via linkml-validate\n")
        try:
            validator = Validator(sv.schema)
            dup_pkg = {
                "element_id": "dams:pkg/spike",
                "name": "spike",
                "description": "spike",
                "lifecycle_status": "draft",
                "api_version": "v1",
                "model_version": "0.1.0",
                "data_carriers": [
                    {**CARRIER},
                    {
                        **CARRIER,
                        "element_id": "dams:asset/spike/carrier2",
                        "name": "carrier2",
                    },
                ],
            }
            report = validator.validate(dup_pkg, target_class="SpikePackageSeparate")
            issues = list(report.results) if report else []
            uk_hit = any(
                "unique" in str(i).lower() or "technical_asset_key" in str(i) for i in issues
            )
            lines.append(f"- duplicate (asset_namespace, qualified_name) issues: {len(issues)}\n")
            lines.append(f"- unique_keys triggered: {uk_hit}\n")
            for i in issues[:8]:
                lines.append(f"  - `{i}`\n")
        except Exception as exc:  # noqa: BLE001
            lines.append(f"- unique_keys check: FAIL — `{exc}`\n")

        lines.append("\n## Variant B: separate collections\n")
        try:
            py_b = PydanticGenerator(str(spike_path)).serialize()
            for marker in (
                "data_carriers",
                "access_points",
                "data_containers",
                "execution_assets",
            ):
                idx = py_b.find(marker)
                snippet = py_b[max(0, idx - 40) : idx + 160] if idx >= 0 else "NOT FOUND"
                lines.append(f"- pydantic `{marker}`: `{snippet.replace(chr(10), ' ')}`\n")
            js_b = JsonSchemaGenerator(
                str(spike_path),
                include_range_class_descendants=False,
                top_class="SpikePackageSeparate",
            ).serialize()
            data_b = json.loads(js_b)
            props_b = data_b.get("properties") or {}
            for key in (
                "data_carriers",
                "access_points",
                "data_containers",
                "execution_assets",
            ):
                frag = props_b.get(key) or {}
                lines.append(f"- json-schema `{key}`: `{json.dumps(frag)[:300]}`\n")
            lines.append("- Variant B generation: OK\n")
        except Exception as exc:  # noqa: BLE001
            lines.append(f"- Variant B: FAIL — `{exc}`\n")

        lines.append("\n## Round-trip probe (Pydantic instantiate subclass fields)\n")
        try:
            mod_path = tmp_path / "spike_models.py"
            mod_path.write_text(PydanticGenerator(str(spike_path)).serialize(), encoding="utf-8")
            import importlib.util

            spec = importlib.util.spec_from_file_location("spike_models", mod_path)
            assert spec and spec.loader
            mod = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(mod)

            poly_ok = False
            poly_msg = ""
            if hasattr(mod, "DataCarrier"):
                try:
                    carrier = mod.DataCarrier(
                        **{k: v for k, v in CARRIER.items() if k != "system_ref"}
                    )
                    poly_msg = (
                        f"DataCarrier alone: type={type(carrier).__name__}, "
                        f"structure_ref={getattr(carrier, 'structure_ref', None)}"
                    )
                    poly_ok = getattr(carrier, "structure_ref", None) == "oracle:SCHEMA.T1"
                except Exception as exc:  # noqa: BLE001
                    poly_msg = f"DataCarrier instantiate FAIL: {exc}"
            lines.append(f"- {poly_msg}\n")
            lines.append(f"- subclass field preserved: {poly_ok}\n")

            if hasattr(mod, "SpikePackageSeparate"):
                ann = getattr(mod.SpikePackageSeparate, "model_fields", {}) or {}
                for key in (
                    "data_carriers",
                    "access_points",
                    "data_containers",
                    "execution_assets",
                    "technical_assets",
                ):
                    if key in ann:
                        lines.append(
                            f"- SpikePackageSeparate.{key} annotation: `{ann[key].annotation}`\n"
                        )
            if hasattr(mod, "SpikePackagePoly"):
                ann = getattr(mod.SpikePackagePoly, "model_fields", {}) or {}
                if "technical_assets" in ann:
                    lines.append(
                        f"- SpikePackagePoly.technical_assets annotation: "
                        f"`{ann['technical_assets'].annotation}`\n"
                    )
        except Exception as exc:  # noqa: BLE001
            lines.append(f"- Round-trip probe FAIL — `{exc}`\n")

        # Decision heuristic
        lines.append("\n## Decision\n")
        poly_ann = ""
        try:
            if "SpikePackagePoly.technical_assets annotation:" in "".join(lines):
                for line in lines:
                    if "SpikePackagePoly.technical_assets annotation:" in line:
                        poly_ann = line
        except Exception:  # noqa: BLE001
            pass
        collapses = "TechnicalAsset" in poly_ann and "DataCarrier" not in poly_ann
        if collapses or ("Union" not in (py_code or "") and "DataCarrier" not in poly_ann):
            lines.append(
                "**Chosen: Variant B (separate collections).** "
                "Polymorphic `technical_assets` collapses to abstract `TechnicalAsset` "
                "in gen-pydantic / lacks reliable subclass Union. "
                "Unified registry is a computed view in ModelGraph. "
                "unique_keys enforced primarily by DAMS validator.\n"
            )
            decision = "B"
        else:
            lines.append(
                "**Chosen: Variant A (polymorphic technical_assets)** — "
                "generators preserve subclass fields via Union/discriminator.\n"
            )
            decision = "A"
        lines.append(f"\nDecision code: `{decision}`\n")
    finally:
        if spike_path.exists():
            spike_path.unlink()

    out = REPO / "docs" / "migration" / "technical-asset-spike-report.md"
    out.write_text("".join(lines), encoding="utf-8")
    print(f"Wrote {out}")
    print("".join(lines))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
