"""External alignment governance (ADR-020)."""

from moex_modeling.external_alignment.public import (
    CompetencyQuestion,
    ExternalMappingAssertion,
    ExternalMappingRelation,
    ExternalSelectionDecision,
    ExternalSpecificationArea,
    ExternalSpecificationAreaKind,
    ExternalSpecificationKind,
    ExternalSpecificationScope,
    ExternalSpecificationVersion,
    ExternalTermKind,
    ExternalTermSelection,
    ExternalTermSelectionItem,
    ExtractionPlan,
    ExtractionRole,
    MaterializedExternalModule,
    ReviewStatus,
    SelectionBasis,
    SelectionRules,
    SelectionValidationReport,
    UpstreamLocator,
    ValidationIssue,
    scope_from_dict,
    selection_from_dict,
    validate_scope,
    validate_selection,
)

__all__ = [
    "CompetencyQuestion",
    "ExternalMappingAssertion",
    "ExternalMappingRelation",
    "ExternalSelectionDecision",
    "ExternalSpecificationArea",
    "ExternalSpecificationAreaKind",
    "ExternalSpecificationKind",
    "ExternalSpecificationScope",
    "ExternalSpecificationVersion",
    "ExternalTermKind",
    "ExternalTermSelection",
    "ExternalTermSelectionItem",
    "ExtractionPlan",
    "ExtractionRole",
    "MaterializedExternalModule",
    "ReviewStatus",
    "SelectionBasis",
    "SelectionRules",
    "SelectionValidationReport",
    "UpstreamLocator",
    "ValidationIssue",
    "scope_from_dict",
    "selection_from_dict",
    "validate_scope",
    "validate_selection",
]
